# FROM node:18

# RUN npm install -g pnpm

# WORKDIR /app

# COPY package.json pnpm-lock.yaml ./

# RUN pnpm install --frozen-lockfile

# COPY . .

# EXPOSE 3000

# RUN npx prisma generate

# CMD ["sh", "-c", "NODE_PATH=./src pnpm nodemon src/index.ts"]


FROM node:18 AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

COPY . /app

WORKDIR /app

RUN npx prisma generate

FROM base AS dev-deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

FROM base AS dev
COPY --from=dev-deps /app/node_modules /app/node_modules

EXPOSE 3000



CMD ["sh", "-c", "NODE_PATH=./src pnpm nodemon src/index.ts"]
