FROM node:20-alpine

# Set working directory
WORKDIR /usr/src/app

# Install git globally
RUN apk update && apk add --no-cache git

# Install pnpm globally
RUN npm install -g pnpm

# Change ownership of the working directory to the node user
RUN chown -R node:node /usr/src/app

# Switch to a non-root user
USER node

# Copy package.json and pnpm-lock.yaml first to leverage Docker cache
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install

# Copy the rest of the application code
COPY --chown=node:node . .

# Ensure Prisma CLI is installed and Prisma client is generated
RUN pnpm prisma generate

# Expose the application port
EXPOSE 3000

# Start the application with nodemon
CMD ["pnpm", "nodemon", "--watch", "src", "src/index.ts"]