version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    # develop:
    #   watch:
    #     - path: ./package.json
    #       action: rebuild
    #     - path: ./pnpm-lock.yaml
    #       action: rebuild
    #     - path: ./src
    #       target: /usr/src/app/src
    #       action: sync
    #     - path: ./prisma
    #       target: /usr/src/app/prisma
    #       action: sync
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  db_admin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db

volumes:
  postgres-data:
